exclude = [".git", ".mypy_cache", ".ruff_cache", ".venv", "dist"]

# Support Python 3.10+.
target-version = "py310"
# Set the maximum line length to 120.
line-length = 120
# In addition to the standard set of exclusions, omit all tests, plus a specific file.
extend-exclude = ["tests"]

[format]
preview = true
quote-style = "single"
docstring-code-format = true
docstring-code-line-length = 80

[lint]
# Add the `line-too-long` rule to the enforced rule set.
extend-select = ["E501"]

[lint.per-file-ignores]
"**/scripts/*" = [
  "INP001",
  "T201",
]
"**/tests/**/*" = [
  "PLC1901",
  "PLR2004",
  "PLR6301",
  "S",
  "TID252",
]
